{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      " * Serving Flask app '__main__'\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[31m\u001b[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.\u001b[0m\n",
      " * Running on http://127.0.0.1:8050\n",
      "\u001b[33mPress CTRL+C to quit\u001b[0m\n",
      "127.0.0.1 - - [19/Dec/2023 20:19:31] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Dec/2023 20:19:31] \"GET /_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_14_1m1699969287.min.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Dec/2023 20:19:31] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Dec/2023 20:19:31] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Dec/2023 20:19:31] \"\u001b[36mGET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1\u001b[0m\" 304 -\n",
      "127.0.0.1 - - [19/Dec/2023 20:19:31] \"\u001b[36mGET /_dash-component-suites/dash/dcc/async-dropdown.js HTTP/1.1\u001b[0m\" 304 -\n",
      "127.0.0.1 - - [19/Dec/2023 20:19:31] \"\u001b[36mGET /_dash-component-suites/plotly/package_data/plotly.min.js HTTP/1.1\u001b[0m\" 304 -\n",
      "127.0.0.1 - - [19/Dec/2023 20:19:31] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Dec/2023 20:19:31] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Dec/2023 20:19:31] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Dec/2023 20:19:31] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Dec/2023 20:19:31] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Dec/2023 20:19:32] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [19/Dec/2023 20:19:32] \"POST /_dash-update-component HTTP/1.1\" 200 -\n"
     ]
    }
   ],
   "source": [
    "import dash\n",
    "from dash import dcc, html, Input, Output\n",
    "import pandas as pd\n",
    "import plotly \n",
    "import plotly.graph_objects as go\n",
    "import plotly.express as px\n",
    "import geopandas as gpd\n",
    "from plotly.subplots import make_subplots\n",
    "\n",
    "# Load data\n",
    "birth_rate_data = pd.read_csv('/Users/hyeongseokkim/Desktop/데이터마이닝 자료/babyboom/data/seoul_birth_ave.csv', encoding='euc-kr')\n",
    "male_employment_data = pd.read_csv('/Users/hyeongseokkim/Desktop/데이터마이닝 자료/babyboom/data/seoul_employ_m.csv', encoding='euc-kr')\n",
    "female_employment_data = pd.read_csv('/Users/hyeongseokkim/Desktop/데이터마이닝 자료/babyboom/data/seoul_employ_w.csv', encoding='euc-kr')\n",
    "sigungu_data = pd.read_csv('/Users/hyeongseokkim/Desktop/데이터마이닝 자료/babyboom/data/seoul_employ_sigungu.csv', encoding='euc-kr')\n",
    "employment_data = pd.merge(male_employment_data, female_employment_data, on='연도', how='inner', suffixes=('_male', '_female'))\n",
    "gdp = pd.read_csv('/Users/hyeongseokkim/Desktop/데이터마이닝 자료/babyboom/data/자치구별 1인당 지역내총생산.csv')\n",
    "marriage_data = pd.read_csv('/Users/hyeongseokkim/Desktop/데이터마이닝 자료/babyboom/data/seoul_mar_ave.csv', encoding='euc-kr')\n",
    "marriage_rate_data = pd.read_csv('/Users/hyeongseokkim/Desktop/데이터마이닝 자료/babyboom/data/seoul_mar_ave.csv', encoding='euc-kr')\n",
    "marriage_data.set_index('연도', inplace=True)\n",
    "rate = pd.read_csv('/Users/hyeongseokkim/Desktop/데이터마이닝 자료/babyboom/data/서울시 합계출산율.csv')\n",
    "pie_income = pd.read_csv('/Users/hyeongseokkim/Desktop/데이터마이닝 자료/babyboom/data/서울시 저출산 원인 소득별.csv')\n",
    "pie_where = pd.read_csv('/Users/hyeongseokkim/Desktop/데이터마이닝 자료/babyboom/data/서울시 저출산 원인 지역별.csv')\n",
    "pie_total = pd.read_csv('/Users/hyeongseokkim/Desktop/데이터마이닝 자료/babyboom/data/서울시 저출산 원인.csv')\n",
    "budongsan2015 = pd.read_csv('/Users/hyeongseokkim/Desktop/데이터마이닝 자료/babyboom/data/2015 last.csv', encoding='euc-kr')\n",
    "budongsan2016 = pd.read_csv('/Users/hyeongseokkim/Desktop/데이터마이닝 자료/babyboom/data/2016 last.csv', encoding='euc-kr')\n",
    "budongsan2017 = pd.read_csv('/Users/hyeongseokkim/Desktop/데이터마이닝 자료/babyboom/data/2017last.csv', encoding='euc-kr')\n",
    "debt = pd.read_csv('/Users/hyeongseokkim/Desktop/데이터마이닝 자료/babyboom/data/Ratio_of_Education_Debt.csv', encoding='utf-8')\n",
    "birthrate = pd.read_csv('/Users/hyeongseokkim/Desktop/데이터마이닝 자료/babyboom/data/자치구별_출산율f.csv', encoding='utf-8')\n",
    "merged_df1 = pd.merge(debt, birthrate, on='자치구별', how='left')\n",
    "finance = pd.read_csv('/Users/hyeongseokkim/Desktop/데이터마이닝 자료/babyboom/data/Educational_Financial_Support.csv', encoding='utf-8')\n",
    "merged_df = pd.merge(finance, birthrate, on='자치구별', how='left')\n",
    "df_2015 = pd.read_csv('/Users/hyeongseokkim/Desktop/데이터마이닝 자료/babyboom/data/2015 last.csv', encoding='euc-kr')\n",
    "df_2016 = pd.read_csv('/Users/hyeongseokkim/Desktop/데이터마이닝 자료/babyboom/data/2016 last.csv', encoding='euc-kr')\n",
    "df_2017 = pd.read_csv('/Users/hyeongseokkim/Desktop/데이터마이닝 자료/babyboom/data/2017last.csv', encoding='euc-kr')\n",
    "education_expense = pd.read_csv('/Users/hyeongseokkim/Desktop/데이터마이닝 자료/babyboom/data/Education_Expense.csv', encoding='euc-kr')\n",
    "birthrate_combined = pd.read_csv('/Users/hyeongseokkim/Desktop/데이터마이닝 자료/babyboom/data/자치구별_출산율f.csv', encoding='utf-8')\n",
    "merged_df_combined = pd.merge(education_expense, birthrate_combined, on='자치구별', how='left')\n",
    "\n",
    "# Add the new code for the Fifty-First Tab with the pie chart\n",
    "df_pie = pd.DataFrame()\n",
    "\n",
    "finance_pie = pd.read_csv('/Users/hyeongseokkim/Desktop/데이터마이닝 자료/babyboom/data/1인가구%.csv', encoding='utf-8')\n",
    "\n",
    "fin_pie = finance_pie.loc[:, ['동별', '1인가구%']].groupby(by='동별', as_index=False).sum()\n",
    "\n",
    "trace_pie = go.Pie(\n",
    "    labels=fin_pie['동별'],\n",
    "    values=fin_pie['1인가구%']\n",
    ")\n",
    "\n",
    "data_pie = [trace_pie]\n",
    "layout_pie = go.Layout(title='1인가구 비율')\n",
    "\n",
    "fig_pie = go.Figure(data_pie, layout_pie)\n",
    "\n",
    "\n",
    "# Load income data for 2019 and 2020\n",
    "data2 = pd.read_csv('/Users/hyeongseokkim/Desktop/데이터마이닝 자료/babyboom/data/소득소비 자치구별.csv', encoding='euc-kr', header=0)\n",
    "data2['Income2019'] = data2['2019년 월 평균 소득 금액']\n",
    "income2019 = data2[['자치구별', 'Income2019']]\n",
    "data2['Income2020'] = data2['2020년 월 평균 소득 금액']\n",
    "income2020 = data2[['자치구별', 'Income2020']]\n",
    "# Create line plot for rate\n",
    "trace1 = go.Scatter(\n",
    "    x=rate['자치구별'],\n",
    "    y=rate['2019'],\n",
    "    mode='lines+markers',\n",
    "    name='rate2019'\n",
    ")\n",
    "\n",
    "trace2 = go.Scatter(\n",
    "    x=rate['자치구별'],\n",
    "    y=rate['2020'],\n",
    "    mode='lines+markers',\n",
    "    name='rate2020'\n",
    ")\n",
    "\n",
    "# Create bar plot for income\n",
    "income_trace1 = go.Bar(\n",
    "    x=data2['자치구별'],\n",
    "    y=data2['Income2019'],\n",
    "    name='Income2019',\n",
    "    marker=dict(color='blue'),\n",
    "    visible=False\n",
    ")\n",
    "income_trace2 = go.Bar(\n",
    "    x=data2['자치구별'],\n",
    "    y=data2['Income2020'],\n",
    "    name='Income2020',\n",
    "    marker=dict(color='blue'),\n",
    "    visible=False\n",
    ")\n",
    "\n",
    "\n",
    "\n",
    "# Create subplot\n",
    "fig = make_subplots(rows=2, cols=1, shared_xaxes=True, subplot_titles=('Rate 2019~2020', 'Income in Seoul 2019~2020'))\n",
    "\n",
    "# Add traces to subplot\n",
    "fig.add_trace(trace1, row=1, col=1)\n",
    "fig.add_trace(trace2, row=1, col=1)\n",
    "fig.add_trace(income_trace1, row=2, col=1)\n",
    "fig.add_trace(income_trace2, row=2, col=1)\n",
    "\n",
    "# Update layout\n",
    "fig.update_layout(height=600, width=800, title_text=\"Rate and Income in Seoul 2019~2020, 서울열린데이터광장\", showlegend=True)\n",
    "\n",
    "\n",
    "marriage_traces = []\n",
    "for column in marriage_data.columns:\n",
    "    marriage_trace = go.Scatter(x=marriage_data.index, y=marriage_data[column], mode='lines', name=column)\n",
    "    marriage_traces.append(marriage_trace)\n",
    "\n",
    "marriage_layout = go.Layout(\n",
    "    title='서울 평균 혼인율 (2000년 - 2022년)',\n",
    "    xaxis=dict(title='연도'),\n",
    "    yaxis=dict(title='평균 혼인율'),\n",
    "    showlegend=True\n",
    ")\n",
    "\n",
    "\n",
    "years = ['2015', '2016', '2017']\n",
    "# Initialize the Dash app\n",
    "app = dash.Dash(__name__)\n",
    "server = app.server\n",
    "\n",
    "# Define the layout of the dashboard\n",
    "app.layout = html.Div(children=[\n",
    "    html.H1(children='What are the factors that influence the birth rate?',style = {'textAlign': 'center', \n",
    "                     'marginBottom': 10, \n",
    "                     'marginTop': 10}),\n",
    "\n",
    "   \n",
    "    html.Div([\n",
    "        dcc.Dropdown(\n",
    "            id='activity-dropdown',\n",
    "            options=[\n",
    "                {'label': 'Male Economic Activity Participation Rate', 'value': '남자경제활동참가율'},\n",
    "                {'label': 'Female Economic Activity Participation Rate', 'value': '여자경제활동참가율'}\n",
    "            ],\n",
    "            value='남자경제활동참가율',\n",
    "            style={'width': '50%'}\n",
    "        ),\n",
    "        dcc.Dropdown(\n",
    "            id='additional-data-dropdown',\n",
    "            options=[\n",
    "                {'label': 'Average Marriage Rate', 'value': '평균혼인율'}\n",
    "            ],\n",
    "            value='평균혼인율',\n",
    "            style={'width': '50%'}\n",
    "        ),\n",
    "        dcc.Graph(\n",
    "            id='combined-chart',\n",
    "            figure=px.bar(\n",
    "                birth_rate_data,\n",
    "                x='연도',\n",
    "                y='합계출산율',\n",
    "                title='Birth Rate and Economic Activity Participation Rates Over Years, kosis 국가통계포털'\n",
    "            ).update_traces(marker_color='rgba(152, 0, 0, 0.5)').update_layout(\n",
    "                yaxis=dict(title='Birth Rate'),\n",
    "                xaxis=dict(title='Year'),\n",
    "                barmode='group',\n",
    "                yaxis2=dict(\n",
    "                    title='Economic Activity Participation Rate',\n",
    "                    overlaying='y',\n",
    "                    side='right'\n",
    "                ),\n",
    "                yaxis3=dict(\n",
    "                    title='Average Marriage Rate',\n",
    "                    overlaying='y',\n",
    "                    side='right',\n",
    "                    position=0.85\n",
    "                )\n",
    "            )\n",
    "        )\n",
    "    ]),\n",
    "\n",
    "    # Content for the second tab\n",
    "    html.Div([\n",
    "        dcc.Dropdown(\n",
    "            id='total-dropdown',\n",
    "            options=[{'label': value, 'value': value} for value in pie_total['특성별'].unique()],\n",
    "            value=pie_total['특성별'].unique()[0],\n",
    "            multi=False\n",
    "        ),\n",
    "        dcc.Graph(id='pie-total')\n",
    "    ]),\n",
    "\n",
    "    # Content for the third tab\n",
    "    html.Div([\n",
    "        dcc.Dropdown(\n",
    "            id='year-dropdown',\n",
    "            options=[\n",
    "                {'label': '2019', 'value': '2019'},\n",
    "                {'label': '2020', 'value': '2020'}\n",
    "            ],\n",
    "            value='2019',\n",
    "            style={'width': '50%'}\n",
    "        ),\n",
    "        dcc.Graph(\n",
    "            id='rate-income-chart',\n",
    "            figure=fig\n",
    "        )\n",
    "    ]),\n",
    "    dcc.Tab(label='Real Estate Dashboard', children=[\n",
    "            html.Div([\n",
    "                html.H2(\"Seoul Real Estate Dashboard\"),\n",
    "\n",
    "                # Dropdown for selecting the year\n",
    "                dcc.Dropdown(\n",
    "                    id='year-dropdown2',\n",
    "                    options=[\n",
    "                        {'label': '2015', 'value': '2015'},\n",
    "                        {'label': '2016', 'value': '2016'},\n",
    "                        {'label': '2017', 'value': '2017'}\n",
    "                    ],\n",
    "                    value='2015',\n",
    "                    style={'width': '50%'}\n",
    "                ),\n",
    "\n",
    "                # Graph component for displaying plots\n",
    "                dcc.Graph(id='dashboard-graph')\n",
    "            ])\n",
    "        ]),\n",
    "\n",
    "        # First Tab\n",
    "        dcc.Tab(label='Birthrate and Education Debt Ratio', children=[\n",
    "            html.Div([\n",
    "                html.H2(\"Birthrate and Education Debt Ratio Dashboard\"),\n",
    "                dcc.Dropdown(\n",
    "                    id='year-dropdown1',\n",
    "                    options=[{'label': str(year), 'value': str(year)} for year in range(2007, 2015)],\n",
    "                    value='2007',\n",
    "                    style={'width': '50%'}\n",
    "                ),\n",
    "                dcc.Graph(id='subplot-graph')\n",
    "            ]),\n",
    "        ]),\n",
    "\n",
    "        # Third Tab\n",
    "        dcc.Tab(label='Educational Finance Dashboard', children=[\n",
    "            html.Div([\n",
    "                html.H2(\"Educational Finance Dashboard\"),\n",
    "\n",
    "                dcc.Dropdown(\n",
    "                    id='year-dropdown-education',\n",
    "                    options=[\n",
    "                        {'label': f'Year {year}', 'value': year} for year in range(2007, 2015)\n",
    "                    ],\n",
    "                    value='2007',\n",
    "                    style={'width': '50%'}\n",
    "                ),\n",
    "                dcc.Graph(id='education-dashboard-plot')\n",
    "            ])\n",
    "        ]),\n",
    "\n",
    "        # Fourth Tab\n",
    "        dcc.Tab(label='Choropleth Map', children=[\n",
    "            html.Div([\n",
    "                html.H2(\"Choropleth Map of 1인가구 비율\"),\n",
    "\n",
    "                dcc.Dropdown(\n",
    "                    id='year-dropdown-choropleth',\n",
    "                    options=[\n",
    "                        {'label': 'Year 1', 'value': 'Year1'},\n",
    "                      \n",
    "                    ],\n",
    "                    value='Year1',\n",
    "                    style={'width': '50%'}\n",
    "                ),\n",
    "\n",
    "                dcc.Graph(id='choropleth-map')\n",
    "            ])\n",
    "        ]),\n",
    "\n",
    "\n",
    "])\n",
    "\n",
    "\n",
    "# Define callback to update chart based on dropdown selections\n",
    "@app.callback(\n",
    "    Output('combined-chart', 'figure'),\n",
    "    [Input('activity-dropdown', 'value'),\n",
    "     Input('additional-data-dropdown', 'value')]\n",
    ")\n",
    "def update_chart(selected_activity, selected_additional_data):\n",
    "    trace1 = go.Scatter(\n",
    "        x=birth_rate_data['연도'], \n",
    "        y=employment_data[selected_activity], \n",
    "        name=selected_activity,\n",
    "        line=dict(color='blue'),\n",
    "        yaxis='y2'\n",
    "    )\n",
    "\n",
    "    trace2 = go.Scatter(\n",
    "        x=marriage_rate_data['연도'], \n",
    "        y=marriage_rate_data[selected_additional_data], \n",
    "        name=selected_additional_data,\n",
    "        line=dict(color='green'),\n",
    "        yaxis='y3'\n",
    "    )\n",
    "\n",
    "    figure = px.bar(\n",
    "        birth_rate_data, \n",
    "        x='연도', \n",
    "        y='합계출산율', \n",
    "        title=f'Birth Rate and {selected_activity} Over Years, kosis 국가통계포털'\n",
    "    ).update_traces(marker_color='rgba(152, 0, 0, 0.5)').update_layout(\n",
    "        yaxis=dict(title='Birth Rate'),\n",
    "        xaxis=dict(title='Year'),\n",
    "        barmode='group',\n",
    "        yaxis2=dict(\n",
    "            title='Economic Activity Participation Rate',\n",
    "            overlaying='y',\n",
    "            side='right'\n",
    "        ),\n",
    "        yaxis3=dict(\n",
    "            title='Average Marriage Rate',\n",
    "            overlaying='y',\n",
    "            side='right',\n",
    "            position=0.85\n",
    "        )\n",
    "    ).add_trace(trace1).add_trace(trace2)\n",
    "\n",
    "    return figure\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "   \n",
    "@app.callback(\n",
    "    Output('rate-income-chart', 'figure'),\n",
    "    [Input('year-dropdown', 'value')]\n",
    ")\n",
    "def update_chart(selected_year1):\n",
    "    # Update the visibility of traces based on the selected year\n",
    "    fig.update_traces(visible='legendonly')\n",
    "    if selected_year1 == '2019':\n",
    "        fig.update_traces(visible=True, selector=dict(name='rate2019'))\n",
    "        fig.update_traces(visible=True, selector=dict(name='Income2019'))\n",
    "    elif selected_year1 == '2020':\n",
    "        fig.update_traces(visible=True, selector=dict(name='rate2020'))\n",
    "        fig.update_traces(visible=True, selector=dict(name='Income2020'))\n",
    "\n",
    "    return fig\n",
    "\n",
    "# Helper function to create a pie chart based on dropdown value\n",
    "def create_pie_chart(data, dropdown_value):\n",
    "    selected_data = data[data['특성별'] == dropdown_value]\n",
    "    fig = make_subplots(rows=1, cols=1)\n",
    "    \n",
    "    for index, row in selected_data.iterrows():\n",
    "        trace = go.Pie(labels=data.columns[2:], values=row[2:], name=row['특성별'])\n",
    "        fig.add_trace(trace)\n",
    "\n",
    "    fig.update_layout(\n",
    "        title='출산 부담 원인, 서울열린데이터광장',\n",
    "        showlegend=True\n",
    "    )\n",
    "    \n",
    "    return fig\n",
    "\n",
    "# Callbacks to update the pie charts based on dropdown values\n",
    "\n",
    "\n",
    "@app.callback(Output('pie-total', 'figure'), [Input('total-dropdown', 'value')])\n",
    "def update_pie_total(selected_value):\n",
    "    return create_pie_chart(pie_total, selected_value)\n",
    "\n",
    "\n",
    "\n",
    "# Callbacks for the first app\n",
    "@app.callback(\n",
    "    Output('subplot-graph', 'figure'),\n",
    "    [Input('year-dropdown1', 'value')]\n",
    ")\n",
    "def update_graph1(selected_year):\n",
    "    bar_trace = go.Bar(x=merged_df1['자치구별'], y=merged_df1[f'{selected_year}_y'], name='출산율')\n",
    "    line_trace = go.Scatter(x=merged_df1['자치구별'], y=merged_df1[f'{selected_year}_x'], mode='lines', name='부채 중 교육비 비율')\n",
    "\n",
    "    fig = make_subplots(rows=1, cols=1, specs=[[{'secondary_y': True}]])\n",
    "    fig.add_trace(bar_trace, secondary_y=False)\n",
    "    fig.add_trace(line_trace, secondary_y=True)\n",
    "\n",
    "    fig.update_layout(title_text=f'{selected_year}년 출산율과 부채 중 교육비 비율, 서울열린데이터광장')\n",
    "    fig.update_xaxes(title_text='자치구별')\n",
    "    fig.update_yaxes(title_text='출산율', secondary_y=False)\n",
    "    fig.update_yaxes(title_text='부채 중 교육비 비율', secondary_y=True)\n",
    "\n",
    "    return fig\n",
    "\n",
    "# Callbacks for the second app\n",
    "@app.callback(\n",
    "    Output('dashboard-graph', 'figure'),\n",
    "    [Input('year-dropdown2', 'value')]\n",
    ")\n",
    "def update_graph2(selected_year):\n",
    "    # Select DataFrame based on the selected year\n",
    "    if selected_year == '2015':\n",
    "        df = df_2015\n",
    "    elif selected_year == '2016':\n",
    "        df = df_2016\n",
    "    elif selected_year == '2017':\n",
    "        df = df_2017\n",
    "\n",
    "    # Create subplot\n",
    "    fig = make_subplots(specs=[[{'secondary_y': True}]])\n",
    "    fig.add_trace(go.Scatter(x=df['시군구'], y=df['출산율'], mode='lines', name='출산율'), secondary_y=True)\n",
    "    fig.add_trace(go.Bar(x=df['시군구'], y=df['평당가격'], name='부동산 가격'), secondary_y=False)\n",
    "\n",
    "    # Update layout\n",
    "    fig.update_layout(\n",
    "        title_text=f'{selected_year} 서울시 시군구 부동산 가격, 국토교통부 실거래가 공개시스템',\n",
    "        xaxis_title='시군구',\n",
    "        yaxis_title='Y1 Axis',\n",
    "        height=400\n",
    "    )\n",
    "    fig.update_yaxes(title_text='부동산 가격', secondary_y=False)\n",
    "    fig.update_yaxes(title_text='출산율', secondary_y=True)\n",
    "\n",
    "    return fig\n",
    "\n",
    "# Callbacks for the third app (Updated with the Fourth Tab code)\n",
    "@app.callback(\n",
    "    Output('education-dashboard-plot', 'figure'),\n",
    "    [Input('year-dropdown-education', 'value')]\n",
    ")\n",
    "def update_education_dashboard(selected_year):\n",
    "    fig = make_subplots(rows=2, cols=1, specs=[[{'secondary_y': True}], [{'secondary_y': True}]])\n",
    "\n",
    "    bar_trace = go.Bar(x=merged_df['자치구별'], y=merged_df[f'{selected_year}_y'], name=f'출산율 {selected_year}')\n",
    "    line_trace = go.Scatter(x=merged_df['자치구별'], y=merged_df[f'{selected_year}_x'], mode='lines',\n",
    "                           name=f'교육재정지원현황 {selected_year}')\n",
    "\n",
    "    fig.add_trace(bar_trace, row=1, col=1, secondary_y=False)\n",
    "    fig.add_trace(line_trace, row=1, col=1, secondary_y=True)\n",
    "\n",
    "    fig.update_layout(title_text=f'{selected_year}년 출산율과 교육재정지원현황, 서울열린데이터광장', height=800, width=1000)\n",
    "    fig.update_xaxes(title_text='자치구별', row=2, col=1)\n",
    "    fig.update_yaxes(title_text='출산율', secondary_y=False, row=1, col=1)\n",
    "    fig.update_yaxes(title_text='교육재정지원현황', secondary_y=True, row=1, col=1)\n",
    "\n",
    "    return fig\n",
    "# Callbacks for the fourth app (Choropleth Map)\n",
    "@app.callback(\n",
    "    Output('choropleth-map', 'figure'),\n",
    "    [Input('year-dropdown-choropleth', 'value')]\n",
    ")\n",
    "def update_choropleth_map(selected_year):\n",
    "    finance = pd.read_csv('/Users/hyeongseokkim/Desktop/데이터마이닝 자료/babyboom/data/1인가구%.csv', encoding='utf-8')\n",
    "    seoul_emd = gpd.read_file('/Users/hyeongseokkim/Desktop/데이터마이닝 자료/babyboom/data/LARD_ADM_SECT_SGG_11.shp', encoding='euc-kr').to_crs(4326)\n",
    "    seoul_emd = pd.merge(seoul_emd, finance, left_on='SGG_NM', right_on='동별', how='left')\n",
    "    seoul_emd_json = seoul_emd.__geo_interface__\n",
    "\n",
    "    trace = go.Choroplethmapbox(\n",
    "        geojson=seoul_emd_json,\n",
    "        locations=seoul_emd.index,\n",
    "        z=seoul_emd['1인가구%'],\n",
    "        colorscale=\"Viridis\"\n",
    "    )\n",
    "\n",
    "    layout = go.Layout(\n",
    "        title=f'1인가구 비율 - {selected_year}, kosis 국가통계포털',\n",
    "        mapbox_style=\"carto-positron\",\n",
    "        mapbox_zoom=8.5,\n",
    "        mapbox_center={\"lat\": 37.6, \"lon\": 127}\n",
    "    )\n",
    "\n",
    "    fig = go.Figure(trace, layout)\n",
    "    return fig\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "# Define callback to update graph based on dropdown selections\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "# Run the app\n",
    "if __name__ == '__main__':\n",
    "    app.run_server(debug=False)\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Index(['자치구별', 'birth_rate', 'year'], dtype='object')\n"
     ]
    }
   ],
   "source": [
    "print(rate.columns)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Index(['자치구별', '2019년 월 평균 소득 금액', '2020년 월 평균 소득 금액', 'Income2019',\n",
      "       'Income2020'],\n",
      "      dtype='object')\n"
     ]
    }
   ],
   "source": [
    "print(data2.columns)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
